# Generated by Django 2.2 on 2019-05-23 01:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': '关于我们'},
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='分类:公司简介 组织架构 合作伙伴 荣誉资质 联系我们', max_length=30, verbose_name='标题'),
        ),
    ]
