# Generated by Django 2.2 on 2019-05-23 02:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20190523_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('type', models.SmallIntegerField(choices=[(1, '三十万级净化工程'), (2, '十万级净化工程'), (3, '万级净化工程'), (4, '千级净化工程'), (5, '百级净化工程')], verbose_name='分类')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='工程案例介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '工程案例',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='新闻分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '新闻分类',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='产品分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '产品分类',
            },
        ),
        migrations.CreateModel(
            name='SolutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='解决方案分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '解决方案分类',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.SmallIntegerField(choices=[(1, '公司简介'), (2, '文化理念'), (3, '荣誉资质'), (4, '联系我们')], max_length=30, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='净化方案标题')),
                ('cover', models.ImageField(help_text='（360*258）像素', upload_to='solution_cover/', verbose_name='封面图片')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='净化方案详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.SolutionType', verbose_name='解决方案')),
            ],
            options={
                'verbose_name_plural': '净化方案',
            },
        ),
        migrations.CreateModel(
            name='ProductImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='cases_img/', verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.cases')),
            ],
            options={
                'verbose_name_plural': '工程案例图集',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品标题')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='产品详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ProductType', verbose_name='产品分类')),
            ],
            options={
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('viewed', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.NewsType')),
            ],
            options={
                'verbose_name_plural': '新闻中心',
            },
        ),
        migrations.AddField(
            model_name='cases',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Product', verbose_name='工程应用设备'),
        ),
        migrations.AddField(
            model_name='cases',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.SolutionType', verbose_name='解决方案'),
        ),
    ]
