# Generated by Django 2.2 on 2019-05-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20190523_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='casesimgs',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='productimgs',
            name='product',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='type',
        ),
        migrations.DeleteModel(
            name='cases',
        ),
        migrations.DeleteModel(
            name='CasesImgs',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImgs',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='SolutionType',
        ),
    ]
