# Generated by Django 2.2 on 2019-06-17 08:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SmallIntegerField(choices=[(1, '公司简介'), (2, '文化理念'), (3, '联系我们')], verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '关于我们',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='建议图片大小：1920*680像素', upload_to='banner/', verbose_name='图片')),
                ('url', models.CharField(max_length=150, verbose_name='图片链接地址')),
                ('open', models.CharField(choices=[('_self', '当前窗口'), ('_blank', '新窗口')], default='当前窗口', max_length=20, verbose_name='链接打开方式')),
                ('order', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default='0', help_text='数值越小排序越前', verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=True, help_text='勾选表示可用', verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '轮番图片',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('type', models.SmallIntegerField(choices=[(1, '三十万级净化工程'), (2, '十万级净化工程'), (3, '万级净化工程'), (4, '千级净化工程'), (5, '百级净化工程')], verbose_name='分类')),
                ('cover', models.ImageField(default='cases_cover/cases_cover.jpg', help_text='建议图片大小：360*258像素', upload_to='cases_cover/', verbose_name='封面图片')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='工程案例介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '      工程案例',
            },
        ),
        migrations.CreateModel(
            name='Honer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('images', models.ImageField(upload_to='honer_img/', verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': ' 荣誉资质',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SmallIntegerField(choices=[(1, '顺尚动态'), (2, '行业资讯'), (3, '净化技术')], verbose_name='新闻分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '    新闻分类',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(verbose_name='车间面积(m²)')),
                ('level', models.IntegerField(verbose_name='净化级别')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(verbose_name='性别')),
                ('mobile', models.IntegerField(verbose_name='手机号')),
            ],
            options={
                'verbose_name_plural': '      客户报价表',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品标题')),
                ('sub_type', models.CharField(default='', max_length=100, verbose_name='产品二级分类')),
                ('cover', models.ImageField(default='products_cover/products_cover.jpg', help_text='建议图片大小：360*258像素', upload_to='news_cover/', verbose_name='封面图片')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='产品详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '         产品',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='产品分类')),
                ('order', models.SmallIntegerField(default='0', help_text='数值越小排序越前', verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '          产品分类',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': ' 售后服务',
            },
        ),
        migrations.CreateModel(
            name='SolutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='解决方案分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '       解决方案分类',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='净化方案标题')),
                ('cover', models.ImageField(help_text='建议图片大小：360*258像素', upload_to='solution_cover/', verbose_name='封面图片')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='净化方案详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SolutionType', verbose_name='解决方案')),
            ],
            options={
                'verbose_name_plural': '      净化方案',
            },
        ),
        migrations.CreateModel(
            name='ProductImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product_img/', verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name_plural': '        产品图集',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductType', verbose_name='产品分类'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('cover', models.ImageField(default='news_cover/news_cover.jpg', help_text='建议图片大小：360*258像素', upload_to='news_cover/', verbose_name='封面图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('viewed', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NewsType', verbose_name='新闻分类')),
            ],
            options={
                'verbose_name_plural': '   新闻中心',
            },
        ),
        migrations.CreateModel(
            name='CasesImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='cases_img/', verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cases')),
            ],
            options={
                'verbose_name_plural': '     工程案例图集',
            },
        ),
        migrations.AddField(
            model_name='cases',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SolutionType', verbose_name='解决方案'),
        ),
    ]
