# Generated by Django 2.2 on 2019-06-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品大类')),
            ],
            options={
                'verbose_name_plural': '          产品大类',
            },
        ),
        migrations.AddField(
            model_name='producttype',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
            preserve_default=False,
        ),
    ]
