# Generated by Django 2.2 on 2019-05-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190523_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.SmallIntegerField(choices=[(1, '公司简介'), (2, '文化理念'), (3, '荣誉资质'), (4, '联系我们')], verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='title',
            field=models.SmallIntegerField(choices=[(1, '顺尚动态'), (2, '行业资讯'), (3, '净化技术')], verbose_name='新闻分类'),
        ),
    ]
