# Generated by Django 2.2 on 2019-06-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190617_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='Category',
            new_name='category',
        ),
    ]
