# Generated by Django 2.2 on 2019-05-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190523_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Product', verbose_name='工程应用设备'),
        ),
    ]
