# Generated by Django 2.2 on 2019-05-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190523_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='products',
        ),
    ]
