# Generated by Django 2.2 on 2019-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190617_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_type',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='产品二级分类'),
        ),
    ]
