# Generated by Django 2.2 on 2019-06-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190618_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutiontype',
            name='order',
            field=models.SmallIntegerField(default='0', help_text='数值越小排序越前', verbose_name='排序'),
        ),
    ]
