# Generated by Django 2.2 on 2019-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190523_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.SmallIntegerField(choices=[(1, '公司简介'), (2, '文化理念'), (3, '联系我们'), (4, '444')], verbose_name='标题'),
        ),
    ]
