# Generated by Django 2.2 on 2019-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190621_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='order',
            field=models.SmallIntegerField(default='0', help_text='数值越小排序越前', verbose_name='排序'),
        ),
    ]
