# Generated by Django 2.2 on 2019-05-23 13:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190523_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': ' 售后服务',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.SmallIntegerField(choices=[(1, '公司简介'), (2, '文化理念'), (3, '联系我们')], verbose_name='标题'),
        ),
    ]
