# Generated by Django 2.2 on 2019-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190523_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(default='news_cover/newscover.jpg', help_text='（360*258）像素', upload_to='news_cover/', verbose_name='封面图片'),
        ),
    ]
