# Generated by Django 2.2.2 on 2019-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_solution_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='建议图片大小：1920*300像素', upload_to='head_img/', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '导航图片',
            },
        ),
    ]
