# Generated by Django 2.2 on 2019-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_news_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='products_cover/newscover.jpg', help_text='（360*258）像素', upload_to='news_cover/', verbose_name='封面图片'),
        ),
    ]
