# Generated by Django 2.2 on 2019-05-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cases_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(verbose_name='车间面积')),
                ('level', models.IntegerField(verbose_name='净化级别')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(verbose_name='性别')),
                ('mobile', models.IntegerField(verbose_name='手机号')),
            ],
            options={
                'verbose_name_plural': '      客户报价表',
            },
        ),
    ]
