# Generated by Django 2.2 on 2019-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='area',
            field=models.IntegerField(verbose_name='车间面积(m²)'),
        ),
    ]
