# Generated by Django 2.2 on 2019-05-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
