# Generated by Django 2.2 on 2019-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190529_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='cover',
            field=models.ImageField(default='cases_cover/case_cover.jpg', help_text='建议图片大小：360*258像素', upload_to='cases_cover/', verbose_name='封面图片'),
        ),
    ]
