# Generated by Django 2.2 on 2019-06-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190603_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_type',
            field=models.CharField(default='', max_length=100, verbose_name='产品二级分类'),
        ),
    ]
